<!DOCTYPE html>
<html lang="ru">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <title>Анализатор страниц</title>
</head>
<body class="min-vh-100 d-flex flex-column">
   <header>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
         <a class="navbar-brand" href=<?= $router->urlFor('main') ?>>Анализатор страниц</a>
         <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
               <a class="nav-link active" href=<?= $router->urlFor('main') ?>>Главное</a>
            </li>
            <li class="nav-item">
               <a class="nav-link" href=<?= $router->urlFor('urls') ?>>Сайты</a>
            </li>
         </ul>
      </nav>
   </header>
   <main class="flex-grow-1">
      <div class="container mt-3">
         <div class="row">
            <div class="col-12 col-md-10 col-lg-8 mx-auto border rounded-3 bg-light p-5">
               <h1 class="display-3">Анализатор страниц</h1>
               <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
               <form action=<?= $router->urlFor('setUrl') ?> method="post" class="row">
                  <div class="col-8">
                     <?php if ($errors): ?>
                        <input type="text" name="url[name]" class="form-control form-control-lg is-invalid" placeholder="https://www.example.com" value="<?= htmlspecialchars($url) ?>">
                        <div class="invalid-feedback">Некорректный URL</div>
                     <?php else: ?>
                        <input type="text" name="url[name]" class="form-control form-control-lg" placeholder="https://www.example.com">
                     <?php endif ?>
                  </div>
                  <div class="col-2">
                     <input type="submit" class="btn btn-primary btn-lg ms-3 px-5 text-uppercase mx-3" value="Проверить">
               </form>
            </div>
         </div>
      </div>
   </main>
   <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>