<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
   <title>Анализатор страниц</title>
<title>Анализатор страниц</title>
</head>
<body class="min-vh-100 d-flex flex-column">
   <header class="flex-shrink-0">
      <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
         <a class="navbar-brand" href="/">Анализатор страниц</a>
         <ul class="navbar-nav mr-auto">
            <li class="nav-item">
               <a class="nav-link" href="/">Главное</a>
            </li>
            <li class="nav-item">
               <a class="nav-link active" href="/urls">Сайты</a>
            </li>
         </ul>
      </nav>
      <?php if (count($flash) > 0): ?>
            <?php foreach ($flash as $messages) : ?>
               <?php foreach ($messages as $message) : ?>
                  <div class="alert alert-success" role="alert"><?= $message ?></div>
               <?php endforeach ?>
            <?php endforeach ?>
      <?php endif ?>
   </header>
   <main class="flex-grow-1">
      <div class="container-lg mt-3">
         <h1>Сайт: <?=$url['name']?></h1>
         <div class="table-responsive">
            <table class="table table-bordered table-hover text-nowrap" data-test="url">
               <tbody>
               <tr>
                  <td>ID</td>
                  <td><?=$url['id']?></td>
               </tr>
               <tr>
                  <td>Имя</td>
                  <td><?=$url['name']?></td>
               </tr>
               <tr>
                  <td>Дата создания</td>
                  <td><?=$url['created_at']?></td>
               </tr>
               </tbody>
            </table>
         </div>
         <h2 class="mt-5 mb-3">Проверки</h2>
         <form method="post" action="#">
            <input type="submit" class="btn btn-primary" value="Запустить проверку">
         </form>
         <table class="table table-bordered table-hover" data-test="checks">
            <tbody>
               <tr>
               <th>ID</th>
               <th>Код ответа</th>
               <th>h1</th>
               <th>title</th>
               <th>description</th>
               <th>Дата создания</th>
               </tr>
                  </tbody>
         </table>
      </div>
   </main>
   <footer class="border-top py-3 mt-5 flex-shrink-0">
        <div class="container-lg">
            <div class="text-center">
                <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>