<html>
   <head>
      <meta charset="UTF-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
      <title>Анализатор страниц</title>
   </head>
   <body class="min-vh-100 d-flex flex-column">
      <header class="flex-shrink-0">
         <nav class="navbar navbar-expand-md navbar-dark bg-dark px-3">
            <a class="navbar-brand" href="/">Анализатор страниц</a>
            <ul class="navbar-nav mr-auto">
               <li class="nav-item">
                  <a class="nav-link" href="/">Главное</a>
               </li>
               <li class="nav-item">
                  <a class="nav-link active" href="/urls">Сайты</a>
               </li>
            </ul>
         </nav>
      </header>
      <main class="flex-grow-1">
         <div class="container-lg mt-3">
            <h1>Сайты</h1>
            <table class="table table-bordered table-hover text-nowrap" data-test="urls">
               <tbody>
                  <tr>
                     <th>ID</th>
                     <th>Имя</th>
                     <th>Последняя проверка</th>
                  </tr>
                  <?php foreach($urls as $url): ?>
                  <tr>
                     <td><?=$url['id']?></td>
                     <td>
                        <a href="/urls/<?=$url['id']?>"><?=$url['name']?></a>
                     </td>
                     <td><?=$url['created_at']?></td>
                  </tr>
                  <?php endforeach ?>
               </tbody>
            </table>
         </div>
      </main>
      <footer class="border-top py-3 mt-5 flex-shrink-0">
         <div class="container-lg">
               <div class="text-center">
                  <a href="https://hexlet.io/pages/about" target="_blank">Hexlet</a>
               </div>
         </div>
      </footer>
   </body>
</html>